### ISSUE TITLE
Value error of images

### ISSUE THREAD

**Issue by PratikGajera** [wwoo/tf_box_classify#3]
When i run below script then get following error.

$ python2 tf_convnet_test.py

get_image_label_list: read 460 items
Traceback (most recent call last):
  File "tf_convnet_test.py", line 286, in <module>
    tf.app.run()
  File "/home/test/Tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "tf_convnet_test.py", line 154, in main
    batch_size=TRAIN_BATCH_SIZE, num_epochs=TRAIN_EPOCHS)
  File "tf_convnet_test.py", line 61, in inputs
    image, label = read_image_from_disk(input_queue)
  File "tf_convnet_test.py", line 53, in read_image_from_disk
    rgb_image = tf.image.resize_images(rgb_image, IMAGE_SIZE, IMAGE_SIZE)
  File "/home/test/Tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/image_ops_impl.py", line 659, in resize_images
    raise ValueError('\'size\' must be a 1-D Tensor of 2 elements: '
ValueError: 'size' must be a 1-D Tensor of 2 elements: new_height, new_width

**Comment by wwoo** [comment]
Fixed.  Later versions of TensorFlow changed the resizing parameters to 1-D tensor - i.e. [width, height].
